remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: 2nd TempXAI Workshop @ ECML-PKDD
description: 2nd TempXAI Workshop for Explainable AI in Time Series and Data Streams
show_downloads: false
