remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: 2nd TempXAI Workshop at ECML-PKDD
description: Co-located at ECML-PKDD 2025 in Porto
show_downloads: false
github:
  is_project_page: false
include:
  - assets/css/custom.css
